[17기 남채린] models.py 생성
wecode-bootcamp-korea/17-2nd-tumbluv-backend pull request #1
Opened 2021-03-03 08:46 UTC by namchaerin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 앱 생성 및 models.py 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- user, project, order, message 앱 생성 후 models.py 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-04 02:45 UTC, Kang-kyunghun reviewed
- 전체적으로 max_length 길이 여유롭게 잡아주세요.
- order의 핸드폰번호, 카드번호, 계좌번호 정보와, user의 핸드폰번호, 카드번호, 계좌번호 정보는 어떤 차이가 있는 건가요?(질문)

2021-03-04 02:45 UTC, Kang-kyunghun commented on message/models.py
> +    text       = models.CharField(max_length=1000)
text 내용이 짧은가요? max_length 1000으로 충분한지 궁금합니다.~

2021-03-04 02:45 UTC, Kang-kyunghun commented on order/models.py
> +    account_number = models.CharField(max_length=20)
핸드폰번호, 카드번호, 계좌번호 같은 것은 규격 같은 것이 확실하기 때문에 최대 길이를 잘 잡으신 것 같습니다. 그런데 recipient나 address 같이 길 수도 있는 field는 최대 길이를 여유롭게 잡은면 좋을 것 같습니다.
그리고 컨벤션도 맞춰주세요.

2021-03-04 02:45 UTC, Kang-kyunghun commented on user/models.py
> +    email = models.CharField(max_length=100)
- 10자리 code는 어떤 식으로 생성할 예정이신가요? 
- 컨벤션 맞춰추세요

2021-03-04 02:51 UTC, banana1019 commented on message/models.py
> +    text       = models.CharField(max_length=1000)
2000으로 수정하겠습니다~~

2021-03-04 02:54 UTC, banana1019 commented on order/models.py
> +    account_number = models.CharField(max_length=20)
수정했습니다~~

2021-03-04 04:13 UTC, yoon1ee commented
@Kang-kyunghun 위 코멘트 물어보신부분 답 여기에 남길게요! 텀블벅에는 유저에 default 설정되는 대표 핸드폰번호, 카드번호, 계좌번호가 있는데 이게 주문시에 다른정보로 넣어서 주문도 가능하거든요. 그래서 사용자가 주문할때 기본주소로지정 같은 옵션을 선택하면 user 테이블로 등록이 되고 그렇지 않으면 order 별로 정보를 관리하려고 따로 만들었습니다

2021-03-04 04:33 UTC, namchaerin commented on user/models.py
> +    email = models.CharField(max_length=100)
여섯자리 숫자로 코드를 생성할 예정입니다. 
CharField -> IntegerField 로 수정하겠습니다!

2021-03-04 10:56 UTC, Kang-kyunghun requested changes

2021-03-04 10:56 UTC, Kang-kyunghun commented on order/models.py
> +    status         = models.CharField(max_length=20)
status에 '주문 전' '결제완료' '배송중' 배송완료' 구매확정' 등의 상태가 존재 할 수 있습니다. 이런 상태들을 관리하는 테이블을 따로 만드시면 좋을 것 같습니다.

2021-03-04 10:56 UTC, Kang-kyunghun commented on user/models.py
> +    address          = models.CharField(max_length=500, null=True)
address 테이블을 따로 만드시는 거를 추천 했었는데, 혹시 CharField로 하신 이유가 있을까요?(질문)

2021-03-04 11:09 UTC, banana1019 commented on user/models.py
> +    address          = models.CharField(max_length=500, null=True)
![image](https://user-images.githubusercontent.com/73244322/109955102-724f6580-7d25-11eb-9680-79694363ce4f.png)

2021-03-04 11:11 UTC, banana1019 commented on user/models.py
> +    address          = models.CharField(max_length=500, null=True)
배송지 추가 시 주소만 입력하는게 아니라 이름, 핸드폰 번호까지 입력해야해서 recipients 테이블을 만들어서 한 번에 관리하도록 했습니다~!

2021-03-04 14:31 UTC, yoon1ee commented on order/models.py
> +    status         = models.CharField(max_length=20)
혹시 지금처럼 status 필드 안에서 0, 1, 2 로 상태구분을하게하는건 안좋은가요? 테이블을 따로빼면 그 테이블의 활용도가 있을지 궁금합니다!

2021-03-05 01:32 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-03-05 01:32 UTC, merged