[17기 남채린] ProjectDetailView, unit test 작성
wecode-bootcamp-korea/17-2nd-tumbluv-backend pull request #10
Opened 2021-03-10 12:35 UTC by namchaerin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ProjectDetailView, unit test 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-10 12:51 UTC, Kang-kyunghun requested changes

2021-03-10 12:51 UTC, Kang-kyunghun commented on project/views.py
> +            'story'  : list(project.story_set.values('content')),
values method 대신 list comprehension으로 만들어 보세요

2021-03-10 12:51 UTC, Kang-kyunghun commented on project/views.py
> +                    } for i in range(community.community_set.count())
queryset 자체가 이미 iterable 합니다. 따라서 range를 사용하지 않고, 바로 데이터를 사용할 수 있습니다.
```suggestion
                'recomment'  : [{
                    'user'       :  community.user.fullname,
                    'comment'    : ,
                    'created_at' :  ,
                    } for community in community.community_set.all())
```

2021-03-10 12:51 UTC, Kang-kyunghun commented on project/views.py
> +            }
community가 존재하지 않으면 빈 값들을 보내는 것인가요?
코드 로직에 대해 설명해 주세요.

2021-03-10 15:53 UTC, namchaerin commented on project/views.py
> +            }
네! 존재하지 않을 경우에는 키 값만 보내게 됩니다.

1차 프로젝트 당시 데이터의 유무와 상관없이 형식을 맞춰 주어야 한다는 피드백을 받아서 작성한 것인데
없어도 되는 부분이라면 프론트분들과 상의해 보고 수정하도록 하겠습니다.

2021-03-10 15:53 UTC, namchaerin commented on project/views.py
> +                    } for i in range(community.community_set.count())
왜........저렇게 썼을까요 ㅎㅎ 수정했습니다!

2021-03-10 15:53 UTC, namchaerin commented on project/views.py
> +            'story'  : list(project.story_set.values('content')),
수정했습니다.

2021-03-11 09:24 UTC, Kang-kyunghun requested changes

2021-03-11 09:24 UTC, Kang-kyunghun commented on project/views.py
> +        total_price = []
사용되고 있지 않은 것 같습니다.
제거해 주세요.

2021-03-11 09:24 UTC, Kang-kyunghun commented on project/views.py
> +            'like'             : False if (request.user==None or not project.like_set.filter(user_id=request.user.id).exists()) else True,
```suggestion
            'like'             : False if (request.user is None or not project.like_set.filter(user_id=request.user.id).exists()) else True,
```
None을 판단 할 때는 is를 사용합니다.

2021-03-11 10:00 UTC, namchaerin commented on project/views.py
> +        total_price = []
그렇네요...!제거했습니다!

2021-03-11 10:00 UTC, namchaerin commented on project/views.py
> +            'like'             : False if (request.user==None or not project.like_set.filter(user_id=request.user.id).exists()) else True,
수정했습니다~~

2021-03-11 11:23 UTC, Kang-kyunghun commented
고생 많으셨습니다.~~~

2021-03-11 11:24 UTC, merged