[17기 남채린&허정윤] CREATE: SendMailView, ValidateCodeView, SignUpView
wecode-bootcamp-korea/17-2nd-tumbluv-backend pull request #3
Opened 2021-03-05 04:10 UTC by banana1019

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 View 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 시 이메일 인증 View (6자리 코드 보내기)
- 인증 코드 확인 View
- 회원가입 View

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- .

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-09 02:06 UTC, Kang-kyunghun requested changes

2021-03-09 02:06 UTC, Kang-kyunghun commented on user/views.py
> +
email 존재 여부 확인하는 로직이 이름 길이 검사하는 로직보다 위에 있어야 할 것 같네요. 이름의 길이나 비밀번호의 길이는 결국 회원 가입을 진행하기 위해서 확인 하는 항목이니까요.

2021-03-09 02:06 UTC, Kang-kyunghun commented on user/tests.py
> +
사용한 이유를 알고 싶습니다~

2021-03-09 03:34 UTC, banana1019 commented on user/views.py
> +
생각해보니까 그렇네요..ㅎㅎ 수정했습니다~!

2021-03-09 03:38 UTC, banana1019 commented on user/tests.py
> +
계속 에러가 나서 구글링을 해보니까 저거를 추가하라고 해서 추가해보니까 에러가 안 나더라구요..ㅎㅎ 

에러는 아래와 같습니다
![image](https://user-images.githubusercontent.com/73244322/110414980-56a4e000-80d4-11eb-924c-3b2b6b625594.png)

2021-03-10 11:55 UTC, Kang-kyunghun commented
고생 많으셨습니다.~~!!!

2021-03-10 11:55 UTC, merged