[17기 이지윤] CREATE: 카카오로그인, 유닛테스트
wecode-bootcamp-korea/17-2nd-tumbluv-backend pull request #4
Opened 2021-03-05 13:09 UTC by yoon1ee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오로그인 view, 유닛테스트 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-08 08:33 UTC, Kang-kyunghun requested changes

2021-03-08 08:33 UTC, Kang-kyunghun commented on user/tests.py
> +        self.assertEqual(response.status_code, 401)
status code 뿐 아니라 json data에 대한 test도 포함시켜 주세요.

2021-03-08 08:33 UTC, Kang-kyunghun commented on user/tests.py
> +        self.assertEqual(decoded_id, user_id)
- status code 뿐 아니라 json data에 대한 test도 포함시켜 주세요.
- 위에서 status에 code 확인 후 다시 아래에 다른 코드가 실행 되는 것인가요? test하는 상황이 다른 것 같은데, 이럴 경우 test case을 분리해 주세요.

2021-03-08 14:50 UTC, yoon1ee commented on user/tests.py
> +        self.assertEqual(response.status_code, 401)
status code가 200이 왔다는 자체가 이미 제가 짠 view에서 return 함수가 정상적으로 실행되었다는 뜻인데, 그럼 json data값이 달라질 경우가 전혀 없지 않나요? data에 대한 test도 해야하는 이유가 따로 있을까요...? 🤔

2021-03-08 14:55 UTC, yoon1ee commented on user/tests.py
> +        self.assertEqual(decoded_id, user_id)
-  json data에 대한 부분은 위와 같습니다! 굳이 data에 대한 확인이 필요한 이유를 저는 생각이 안나서 우선 이 부분은 수정없이 pr 올립니다!

-  decoded_id랑 user_id값 비교는 사실 다른 login_decorator를 사용 할 view의 test에서 했어야되는데, 제가 이때 다른 view/test를 짜기 전이여서 확인차 여기 적은걸 그대로 pr 올린 것 같습니다... 삭제 후 다시 pr 올렸습니다!

2021-03-09 01:55 UTC, Kang-kyunghun commented
status 200이 갔다고 해서 정말 내가 원하는 data를 반환 했다고 보장할 수 있을까요?

2021-03-09 05:06 UTC, yoon1ee commented
제가 생각이 짧았습니다 ㅠㅠㅠㅠㅠㅠㅠ 수정해서 올렸습니다!

2021-03-09 07:16 UTC, merged

2021-03-09 07:16 UTC, Kang-kyunghun commented
LGTM!!!